/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApparentTemp: typeof import('./src/components/apparentTemp/apparentTemp.vue')['default']
    DaysPredictorComponent: typeof import('./src/components/daysPredictor/daysPredictorComponent.vue')['default']
    Divider: typeof import('./src/components/utils/divider.vue')['default']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Home: typeof import('./src/components/home.vue')['default']
    HourlyWeatherPredictorComponent: typeof import('./src/components/hourlyPredictor/hourlyWeatherPredictorComponent.vue')['default']
    Humidity: typeof import('./src/components/humidity/humidity.vue')['default']
    HumidityGraph: typeof import('./src/components/humidity/humidityGraph.vue')['default']
    MoonPhase: typeof import('./src/components/moonPhase/moonPhase.vue')['default']
    NotFound: typeof import('./src/components/notFound/notFound.vue')['default']
    PrecipGraph: typeof import('./src/components/precipitation/precipGraph.vue')['default']
    Precipitation: typeof import('./src/components/precipitation/precipitation.vue')['default']
    Pressure: typeof import('./src/components/pressure/pressure.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TempTrend: typeof import('./src/components/tempTrend/tempTrend.vue')['default']
    Test: typeof import('./src/components/test/test.vue')['default']
    TrackSun: typeof import('./src/components/trackSun/trackSun.vue')['default']
    Uvi: typeof import('./src/components/uvi/uvi.vue')['default']
    UviGraph: typeof import('./src/components/uvi/uviGraph.vue')['default']
    VisGraph: typeof import('./src/components/visibility/visGraph.vue')['default']
    Visibility: typeof import('./src/components/visibility/visibility.vue')['default']
    WeatherChart: typeof import('./src/components/bigDataChart/weatherChart.vue')['default']
    WindDirection: typeof import('./src/components/windDirection/windDirection.vue')['default']
  }
}
